# Generated by Django 2.2.5 on 2019-09-16 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['date_created']},
        ),
        migrations.RenameField(
            model_name='album',
            old_name='date_added',
            new_name='date_created',
        ),
    ]
